#!/bin/bash

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║         MeetingAI v4 — Automated GitHub Deployment              ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "✅ Step 1: Create GitHub Repo"
echo "   URL: https://github.com/new"
echo "   Name: meeting-ai"
echo "   Visibility: Public"
echo "   → Create repository"
echo ""
echo "✅ Step 2: Clone to your PC"
echo "   git clone https://github.com/YOUR-USERNAME/meeting-ai.git"
echo "   cd meeting-ai"
echo ""
echo "✅ Step 3: Copy files from $PWD"
echo "   (Copy all files: index.html, README.md, .github/, etc.)"
echo ""
echo "✅ Step 4: Push to GitHub"
echo "   git add ."
echo "   git commit -m 'Initial: MeetingAI v4'"
echo "   git push origin main"
echo ""
echo "✅ Step 5: Enable Pages"
echo "   Repo Settings → Pages → Deploy from branch (main)"
echo "   → Save"
echo ""
echo "✅ Step 6: Open in Android Chrome"
echo "   https://YOUR-USERNAME.github.io/meeting-ai/"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Auto-deployment ready! Every git push = auto-deploy in 30s"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
